### ISSUE TITLE
Improper CIGARs

### ISSUE THREAD

**Issue by mjafin** [Illumina/isaac2#15]
Hi there,
We've come across several improper CIGAR strings produced by isaac and have as a temporary measure addressed them in our variant caller. Could you take a look when you have the time please. Ticket with example data available here:
https://github.com/AstraZeneca-NGS/VarDictJava/issues/37#issuecomment-247366021

**Comment by rpetrovski** [comment]
The example data seems to have been built with iSAAC-01. Both iSAAC-01 and iSAAC-02 are not being supported anymore. Please let me know if the issue still exists with [iSAAC-03](https://github.com/Illumina/isaac3)

Roman.

$ samtools view bam/problem.bam -H |grep VN
@HD VN:1.0  SO:coordinate
@PG ID:iSAAC    PN:iSAAC    CL:/opt/illumina/Isis/2.5.26.13/Workflows/ResequencingWorker/isaac-align -t /home/ec2-user/compute/scratch/isaacTemp -o /home/ec2-user/compute/344404/isaac_align/Alignment -r /opt/genomes/Homo_sapiens/UCSC/hg38-hli/Sequence/IsaacIndex/sorted-reference.xml --base-calls HLVMVCCXX -s HLVMVCCXX/SampleSheetNew.csv --ignore-missing-filters 1 --base-quality-cutoff 15 --use-bases-mask Y150N1,Y150N1 --default-adapters AGATCGGAAGAGCACACGTCTGAACTCCAGTCA_,_TGACTGGAGTTCAGACGTGTGCTCTTCCGATCT --variable-read-length yes --barcode-mismatches 1 --ignore-missing-bcls 1 --stop-at Finish --allow-empty-flowcell 1 --seed-length 32 --cleanup-intermediary 1 --verbosity 3 --start-from Start --lane-number-max 8 --memory-limit 56 --base-calls-format fastq-gz --stats-image-format none --per-tile-tls 1 VN:**iSAAC-01.14.02.06**
