### ISSUE TITLE
Compile on Mac

### ISSUE THREAD

**Issue by zeus19900814** [Illumina/isaac2#3]
Hi,

Does isaac2 compile on MAC or Windows? It compiles perfect on my Linux machine.

I noticed it uses some Linux lib files and I tried to comment them and then compile on MAC with specifying gcc-4.9, but some linking issues occurred. Any manuals or suggestions on compiling on MAC and Windows?

Thank you so much,
Ivan

**Comment by come-raczy** [comment]
Hi Ivan,
No, MAC and windows are not supported at the moment.
Thanks,
Come

**Comment by zeus19900814** [comment]
OK. 
Thank you Come for your quick reply!
