### ISSUE TITLE
isaac-sort-preferenc: space in file path

### ISSUE THREAD

**Issue by zeus19900814** [Illumina/isaac2#4]
Dear Isaac2 developers:

When I use isaac-sort-preference to create a preference to a fasta file, if the file path following -g has a space in it, isaac-sort-preference will throw an error saying "./isaac-sort-reference: line 104: /file/path/before/space/: No such file or directory ERROR: File not found: '/file/path/after/space'".

Error still occurs even though I add "\" before space or quote the whole path.

I am not sure if the same problem happens to other isaac binaries which I haven't tested yet.

Really appreciate your help!

Ivan

**Comment by come-raczy** [comment]
Hi Ivan,

Thanks a lot for pointing it out. We will add this on the TOFIX list.
For now, the easiest workaround is probably to create a symbolic link to
bypass the part of the path that contains the space.

Thanks

Come

**Comment by zeus19900814** [comment]
Hi Come,

Thank you again for the quick feedback!

Sure! I will go with symbolic link at this moment.

Look forward to it being fixed.

Best,
Ivan

**Comment by rpetrovski** [comment]
Ivan, isaac-sort-reference internally uses GNU make to manage the steps of the workflow. Unfortunately make is unable to handle paths with spaces and ':' characters as the whole make syntax is based on the two. It looks like there are not ways to escape those characters nor any development is going on at the moment.

Roman.
