### ISSUE TITLE
Error occurs when isaac-unpack-reference

### ISSUE THREAD

**Issue by zeus19900814** [Illumina/isaac2#5]
Hi Come,

I was doing some testing trying to move around isaac reference files.

First I ran isaac-pack-reference -r /path/to/sorted-reference.xml and then I got packed-reference.tar.gz and a Temp directory which contains .16bpb.gz, a copy of original fasta, sorted-reference.xml and a .sentinel file.

Then how can I unpack the .tar.gz file to the target directory? I tried to run ./isaac-unpack-reference -i packed-reference.tar.gz but I got "../share/iSAAC-02.15.07.16/makefiles/reference/UnpackReferenceSubmake.mk:67: **\* "Expected 1 annotation path, got: ".  Stop.". Am I missing something here?

I didn't see an example in the manual or an input option to specify the output directory.

Thank you,
Ivan

**Comment by come-raczy** [comment]
Hi Ivan,

You are right, there isn't an option to specify the output directory. The
reference will always be unpacked in the current directory. Make sure that
the current directory does not contain a 'Temp' directory.

Thanks,

Come
