### ISSUE TITLE
Aligned reads only have 25 bases.

### ISSUE THREAD

**Issue by zeus19900814** [Illumina/isaac2#7]
Hi Come,

Sorry to bother you so often. Without changing any default parameter values, aligned reads in output bam always only have 25 bases. Is it because the parameter --base-quality-cutoff? I changed it to different value but the number of bases in aligned reads still didn't change.

Please advise how I can keep the original read bases without trimming them in bam file.

Thank you so much!
Ivan

**Comment by rpetrovski** [comment]
if you are aligning from fastq, iSAAC automatically picks the read length
from the first pair of reads it sees. if you want a different one, you need
to use --use-bases-mask yA,yB for paired data or --use-bases-mask yA for
single-ended.

Where A and B are correspondingly read lengths for read one and two.

Roman.

**Comment by zeus19900814** [comment]
Thanks, Roman!

What if I don't have a preference on read lengths? I just want to keep all the original bases?

**Comment by rpetrovski** [comment]
Then you probably should find the longest read in your fastq and use it
with --use-bases-mask. iSAAC was designed to primarily process bcl and with
bcl the read length is pretty straightforward.

**Comment by zeus19900814** [comment]
I see!

Really appreciate your help!
