### ISSUE TITLE
Base quality scores [0-63] supported only.

### ISSUE THREAD

**Issue by zeus19900814** [Illumina/isaac2#8]
Hi,

I was aligning a fastq file and I got the error "Invalid quality 72 found in ....... Base quality scores [0-63] supported only." 
Just realized that the fastq file quality score is Phred+64 encoded. Does Isaac only support Phred+33? 
Can I set some parameters to make it work with Phred+64?

Thanks in advance.
Ivan

**Comment by rpetrovski** [comment]
No, iSAAC expects phred33 qualities from fastq.

Roman.
